### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by mmnewmedia** [StatePol/Database#3]
The data at politician_1.0.3.csv database has wrong matched or not consistent entries  f.e. at line 38: 

Adolf Ernst,/wiki/Adolf_Ernst_(Politiker),FDP,/wiki/Freie_Demokratische_Partei,53.0731864,8.8114816,Asia,South-eastern Asia,Cambodia,KH,ខេត្តបាត់ដំបង,KH-2,,,male

Adolf Ernst was not born in Cambodia, S.E. Asia, but in Althütte, Germany due to his /wiki/Adolf_Ernst_(Politiker) entry, while his birthplace coordinates 53.0731864,8.8114816 point to Bremen, Germany.

**Comment by danielkuhlen** [comment]
Thank you very much for pointing this out, and sorry for the delayed response. The error occurred because some Wikipedia pages for the MPs are formatted differently, resulting in the party being scraped as the birthplace, which led to incorrect birthplace variables. For now, we have set all the birth variables of those cases (20 in total) to NA.

- Daniel
